site_name: BioStore Documentation
# TODO: don't forget to change this!
site_url: https://udel-cbcb.github.io/biostore_docs/
repo_url: https://github.com/udel-cbcb/biostore_docs
edit_uri: edit/main/_docs_src/src
site_description: Documentation for the Biomedical Data Storage Resource (BioStore) at the University of Delaware.
site_author: Amelia O. Harrison
nav: 
  - About BioStore: index.md
  - Using BioStore:
      - Getting Started: getting_started.md
      - Connect from MacOS: mac_connect.md
      - Connect from Windows: windows_connect.md
      - Connect from Linux: linux_connect.md
      - Archiving Data from User Shares: archiving_user_share_data.md
  - Other Resources:
      - FAQs: FAQs.md
theme:
  name: readthedocs
  custom_dir: custom_theme
  # If you need code highlighting set this to true.
  highlightjs: true
  # Pick whichever languages you need to highlight.
  hljs_languages:
    - bash
markdown_extensions:
  - meta
docs_dir: src
site_dir: ../_docs
